/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author minouse3
 */
public class ViewEditUsers extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewEditUsers.class.getName());

    /**
     * Creates new form ViewEditUsers
     */
    public ViewEditUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEditUsers = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textUsername = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        labelNoHp = new javax.swing.JLabel();
        textNoHp = new javax.swing.JTextField();
        labelId6 = new javax.swing.JLabel();
        labelId7 = new javax.swing.JLabel();
        comboxStatus = new javax.swing.JComboBox<>();
        comboxRole = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEditUsers.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelEditUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEditUsers.setText("Edit Users");
        getContentPane().add(labelEditUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        buttonSave.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 170, 40));

        buttonCancel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 170, 40));

        labelId.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelId.setText("ID");
        getContentPane().add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 30));

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));

        labelNama.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelNama.setText("Nama");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, 30));

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });
        getContentPane().add(textNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, 40));

        textUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 230, 40));

        labelUsername.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelUsername.setText("Username");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 230, 30));

        labelEmail.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelEmail.setText("Email");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 30));

        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 40));

        labelPassword.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 230, 30));

        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 230, 40));

        labelNoHp.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelNoHp.setText("No. HP");
        getContentPane().add(labelNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 230, 30));

        textNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNoHpActionPerformed(evt);
            }
        });
        getContentPane().add(textNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 230, 40));

        labelId6.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelId6.setText("Role");
        getContentPane().add(labelId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 30));

        labelId7.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelId7.setText("Status");
        getContentPane().add(labelId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 230, 30));

        comboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Nonaktif" }));
        comboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxStatusActionPerformed(evt);
            }
        });
        getContentPane().add(comboxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 230, 40));

        comboxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Superadmin", "Admin" }));
        comboxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxRoleActionPerformed(evt);
            }
        });
        getContentPane().add(comboxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void textUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsernameActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPasswordActionPerformed

    private void textNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNoHpActionPerformed

    private void comboxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxRoleActionPerformed

    private void comboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxStatusActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewEditUsers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboxRole;
    private javax.swing.JComboBox<String> comboxStatus;
    private javax.swing.JLabel labelEditUsers;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelId6;
    private javax.swing.JLabel labelId7;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNoHp;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNoHp;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
