/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author minouse3
 */
public class ViewEditPromo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewEditPromo.class.getName());

    /**
     * Creates new form ViewEditPromo
     */
    public ViewEditPromo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEditPromo = new javax.swing.JLabel();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelKode = new javax.swing.JLabel();
        textKode = new javax.swing.JTextField();
        textDeskripsi = new javax.swing.JTextField();
        labelDeskripsi = new javax.swing.JLabel();
        labelMinDurasi = new javax.swing.JLabel();
        textMaksimal = new javax.swing.JTextField();
        labelJenis = new javax.swing.JLabel();
        labelNilai = new javax.swing.JLabel();
        labelMaksimal = new javax.swing.JLabel();
        comboxJenis = new javax.swing.JComboBox<>();
        textMinDurasi = new javax.swing.JTextField();
        textNilai = new javax.swing.JTextField();
        labelStart = new javax.swing.JLabel();
        textStart = new javax.swing.JTextField();
        labelEnd = new javax.swing.JLabel();
        textEnd = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        comboxJenis1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEditPromo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelEditPromo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEditPromo.setText("Edit Promo");
        getContentPane().add(labelEditPromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        buttonSave.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 170, 40));

        buttonCancel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 170, 40));

        labelId.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelId.setText("ID");
        getContentPane().add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 30));

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));

        labelKode.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelKode.setText("Kode");
        getContentPane().add(labelKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, 30));

        textKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodeActionPerformed(evt);
            }
        });
        getContentPane().add(textKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, 40));

        textDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDeskripsiActionPerformed(evt);
            }
        });
        getContentPane().add(textDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 230, 240));

        labelDeskripsi.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelDeskripsi.setText("Deskripsi");
        getContentPane().add(labelDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 230, 30));

        labelMinDurasi.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelMinDurasi.setText("Minimal Durasi (Jam)");
        getContentPane().add(labelMinDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 30));

        textMaksimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaksimalActionPerformed(evt);
            }
        });
        getContentPane().add(textMaksimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 230, 40));

        labelJenis.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelJenis.setText("Jenis");
        getContentPane().add(labelJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 230, 30));

        labelNilai.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelNilai.setText("Nilai");
        getContentPane().add(labelNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 30));

        labelMaksimal.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelMaksimal.setText("Maksimal");
        getContentPane().add(labelMaksimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 230, 30));

        comboxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persen", "Nominal" }));
        comboxJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxJenisActionPerformed(evt);
            }
        });
        getContentPane().add(comboxJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 230, 40));

        textMinDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMinDurasiActionPerformed(evt);
            }
        });
        getContentPane().add(textMinDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 40));

        textNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNilaiActionPerformed(evt);
            }
        });
        getContentPane().add(textNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 40));

        labelStart.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelStart.setText("Start (DD-MM-YYYY)");
        getContentPane().add(labelStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 30));

        textStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStartActionPerformed(evt);
            }
        });
        getContentPane().add(textStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, 40));

        labelEnd.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelEnd.setText("End (DD-MM-YYYY)");
        getContentPane().add(labelEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 230, 30));

        textEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEndActionPerformed(evt);
            }
        });
        getContentPane().add(textEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 230, 40));

        labelStatus.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        labelStatus.setText("Status");
        getContentPane().add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 230, 30));

        comboxJenis1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Nonaktif" }));
        comboxJenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxJenis1ActionPerformed(evt);
            }
        });
        getContentPane().add(comboxJenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void textKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodeActionPerformed

    private void textDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDeskripsiActionPerformed

    private void textMinDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMinDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMinDurasiActionPerformed

    private void comboxJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxJenisActionPerformed

    private void textNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNilaiActionPerformed

    private void textMaksimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaksimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaksimalActionPerformed

    private void textStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStartActionPerformed

    private void textEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEndActionPerformed

    private void comboxJenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxJenis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxJenis1ActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewEditPromo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboxJenis;
    private javax.swing.JComboBox<String> comboxJenis1;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel labelEditPromo;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelKode;
    private javax.swing.JLabel labelMaksimal;
    private javax.swing.JLabel labelMinDurasi;
    private javax.swing.JLabel labelNilai;
    private javax.swing.JLabel labelStart;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField textDeskripsi;
    private javax.swing.JTextField textEnd;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textKode;
    private javax.swing.JTextField textMaksimal;
    private javax.swing.JTextField textMinDurasi;
    private javax.swing.JTextField textNilai;
    private javax.swing.JTextField textStart;
    // End of variables declaration//GEN-END:variables
}
