/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author minouse3
 */
public class ViewHomeAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewHomeAdmin.class.getName());

    /**
     * Creates new form ViewHomeAdmin
     */
    public ViewHomeAdmin() {
        initComponents();
        if (Model.UserSession.isLoggedIn()) {
            labelUsername1.setText(Model.UserSession.getUser().getNamaPengguna());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCek = new javax.swing.JButton();
        buttonDataPelanggan = new javax.swing.JButton();
        buttonDataLapangan = new javax.swing.JButton();
        buttonDataBooking = new javax.swing.JButton();
        buttonDataPembayaran = new javax.swing.JButton();
        labelTanggal = new javax.swing.JLabel();
        labelHomeAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLapanganTersedia = new javax.swing.JTable();
        buttonLogOut = new javax.swing.JButton();
        labelUsername1 = new javax.swing.JLabel();
        comboxTanggal = new javax.swing.JComboBox<>();
        labelLapanganTersedia = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        comboxBulan = new javax.swing.JComboBox<>();
        labelTahun = new javax.swing.JLabel();
        comboxTahun = new javax.swing.JComboBox<>();
        labelJenis = new javax.swing.JLabel();
        comboxJenis = new javax.swing.JComboBox<>();
        buttonBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCek.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonCek.setText("Cek");
        buttonCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 130, 40));

        buttonDataPelanggan.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPelanggan.setText("Data Pelanggan");
        buttonDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 40));

        buttonDataLapangan.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataLapangan.setText("Data Lapangan");
        buttonDataLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataLapanganActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 40));

        buttonDataBooking.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataBooking.setText("Data Booking");
        buttonDataBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataBookingActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 40));

        buttonDataPembayaran.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPembayaran.setText(" Data Pembayaran");
        buttonDataPembayaran.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDataPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 40));

        labelTanggal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTanggal.setText("Tanggal*");
        getContentPane().add(labelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 130, 30));

        labelHomeAdmin.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelHomeAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHomeAdmin.setText("HOME");
        getContentPane().add(labelHomeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        tableLapanganTersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Lapangan", "Alamat", "Jenis", "Status"
            }
        ));
        tableLapanganTersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLapanganTersediaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLapanganTersedia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 570, 420));

        buttonLogOut.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 40));

        labelUsername1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsername1.setText("username");
        getContentPane().add(labelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 150, 30));

        comboxTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(comboxTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 130, 30));

        labelLapanganTersedia.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelLapanganTersedia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLapanganTersedia.setText("Lapangan Tersedia");
        getContentPane().add(labelLapanganTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 30));

        labelBulan.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelBulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelBulan.setText("Bulan*");
        getContentPane().add(labelBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 130, 30));

        comboxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxBulanActionPerformed(evt);
            }
        });
        getContentPane().add(comboxBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 130, 30));

        labelTahun.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTahun.setText("Tahun*");
        getContentPane().add(labelTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 130, 30));

        comboxTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTahunActionPerformed(evt);
            }
        });
        getContentPane().add(comboxTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 130, 30));

        labelJenis.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelJenis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJenis.setText("Jenis");
        getContentPane().add(labelJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 130, 30));

        comboxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxJenisActionPerformed(evt);
            }
        });
        getContentPane().add(comboxJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 130, 30));

        buttonBooking.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonBooking.setText("Booking");
        buttonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBookingActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDataBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataBookingActionPerformed

    private void buttonDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataPelangganActionPerformed

    private void buttonDataLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataLapanganActionPerformed

    private void buttonDataPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataPembayaranActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        Model.UserSession.clearSession();
        this.dispose();
        new ViewLogin().setVisible(true);
    }//GEN-LAST:event_buttonLogOutActionPerformed

    private void comboxTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxTanggalActionPerformed

    private void comboxBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxBulanActionPerformed

    private void comboxTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxTahunActionPerformed

    private void comboxJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxJenisActionPerformed

    private void buttonCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCekActionPerformed

    private void buttonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBookingActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tableLapanganTersediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLapanganTersediaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableLapanganTersediaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewHomeAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBooking;
    private javax.swing.JButton buttonCek;
    private javax.swing.JButton buttonDataBooking;
    private javax.swing.JButton buttonDataLapangan;
    private javax.swing.JButton buttonDataPelanggan;
    private javax.swing.JButton buttonDataPembayaran;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JComboBox<String> comboxBulan;
    private javax.swing.JComboBox<String> comboxJenis;
    private javax.swing.JComboBox<String> comboxTahun;
    private javax.swing.JComboBox<String> comboxTanggal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelHomeAdmin;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelLapanganTersedia;
    private javax.swing.JLabel labelTahun;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JTable tableLapanganTersedia;
    // End of variables declaration//GEN-END:variables
}
