/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author minouse3
 */
public class ViewLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewLogin.class.getName());

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        textUsernameEmail = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        labelUsernameEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("LOGIN");
        getContentPane().add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 60));

        textUsernameEmail.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        textUsernameEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textUsernameEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, 40));

        labelPassword.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 460, 30));

        textPassword.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 460, 40));

        buttonLogin.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        buttonLogin.setText("LOGIN");
        getContentPane().add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 460, 50));

        labelUsernameEmail.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelUsernameEmail.setText("Username or Email");
        getContentPane().add(labelUsernameEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 460, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsernameEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsernameEmailActionPerformed

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsernameEmail;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUsernameEmail;
    // End of variables declaration//GEN-END:variables
}
