/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author minouse3
 */
public class ViewHomeSuperadmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewHomeSuperadmin.class.getName());

    /**
     * Creates new form ViewHomeSuperadmin
     */
    public ViewHomeSuperadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCek = new javax.swing.JButton();
        buttonDataPelanggan = new javax.swing.JButton();
        buttonDataLapangan = new javax.swing.JButton();
        buttonDataBooking = new javax.swing.JButton();
        buttonDataPromo = new javax.swing.JButton();
        labelTanggal = new javax.swing.JLabel();
        labelHomeSuperadmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLapanganTersedia = new javax.swing.JTable();
        buttonLogOut = new javax.swing.JButton();
        labelUsername1 = new javax.swing.JLabel();
        comboxTanggal = new javax.swing.JComboBox<>();
        labelLapanganTersedia = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        comboxBulan = new javax.swing.JComboBox<>();
        labelTahun = new javax.swing.JLabel();
        comboxTahun = new javax.swing.JComboBox<>();
        labelJenis = new javax.swing.JLabel();
        comboxJenis = new javax.swing.JComboBox<>();
        buttonBooking = new javax.swing.JButton();
        buttonDataPembayaran = new javax.swing.JButton();
        buttonDataAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCek.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonCek.setText("Cek");
        getContentPane().add(buttonCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 130, 40));

        buttonDataPelanggan.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPelanggan.setText("Data Pelanggan");
        getContentPane().add(buttonDataPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 40));

        buttonDataLapangan.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataLapangan.setText("Data Lapangan");
        getContentPane().add(buttonDataLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 40));

        buttonDataBooking.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataBooking.setText("Data Booking");
        buttonDataBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataBookingActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 40));

        buttonDataPromo.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPromo.setText("Data Promo");
        buttonDataPromo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDataPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataPromoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataPromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 40));

        labelTanggal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTanggal.setText("Tanggal*");
        getContentPane().add(labelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 130, 30));

        labelHomeSuperadmin.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelHomeSuperadmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHomeSuperadmin.setText("HOME");
        getContentPane().add(labelHomeSuperadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        tableLapanganTersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Lapangan", "Alamat", "Jenis", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableLapanganTersedia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 570, 420));

        buttonLogOut.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonLogOut.setText("Log Out");
        getContentPane().add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 40));

        labelUsername1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsername1.setText("username");
        getContentPane().add(labelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 150, 30));

        comboxTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboxTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 130, 30));

        labelLapanganTersedia.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelLapanganTersedia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLapanganTersedia.setText("Lapangan Tersedia");
        getContentPane().add(labelLapanganTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 30));

        labelBulan.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelBulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelBulan.setText("Bulan*");
        getContentPane().add(labelBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 130, 30));

        comboxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboxBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 130, 30));

        labelTahun.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTahun.setText("Tahun*");
        getContentPane().add(labelTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 130, 30));

        comboxTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboxTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 130, 30));

        labelJenis.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelJenis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJenis.setText("Jenis");
        getContentPane().add(labelJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 130, 30));

        comboxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboxJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 130, 30));

        buttonBooking.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonBooking.setText("Booking");
        getContentPane().add(buttonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 130, 40));

        buttonDataPembayaran.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPembayaran.setText(" Data Pembayaran");
        buttonDataPembayaran.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(buttonDataPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 40));

        buttonDataAdmin.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataAdmin.setText("Data Users");
        buttonDataAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataAdminActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDataBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataBookingActionPerformed

    private void buttonDataPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataPromoActionPerformed

    private void buttonDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDataAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewHomeSuperadmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBooking;
    private javax.swing.JButton buttonCek;
    private javax.swing.JButton buttonDataAdmin;
    private javax.swing.JButton buttonDataBooking;
    private javax.swing.JButton buttonDataLapangan;
    private javax.swing.JButton buttonDataPelanggan;
    private javax.swing.JButton buttonDataPembayaran;
    private javax.swing.JButton buttonDataPromo;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JComboBox<String> comboxBulan;
    private javax.swing.JComboBox<String> comboxJenis;
    private javax.swing.JComboBox<String> comboxTahun;
    private javax.swing.JComboBox<String> comboxTanggal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelHomeSuperadmin;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelLapanganTersedia;
    private javax.swing.JLabel labelTahun;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JTable tableLapanganTersedia;
    // End of variables declaration//GEN-END:variables
}
