/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author minouse3
 */
public class ViewHomeAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewHomeAdmin.class.getName());
    private final Controller.LapanganController lapanganController = new Controller.LapanganController();

    /**
     * Creates new form ViewHomeAdmin
     */
    public ViewHomeAdmin() {
        initComponents();
        if (Model.UserSession.isLoggedIn()) {
            labelUsername1.setText(Model.UserSession.getUser().getNamaPengguna());
        }
        setupHomeLapangan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonCek = new javax.swing.JButton();
        buttonDataPelanggan = new javax.swing.JButton();
        buttonDataLapangan = new javax.swing.JButton();
        buttonDataBooking = new javax.swing.JButton();
        buttonDataPembayaran = new javax.swing.JButton();
        labelTanggal = new javax.swing.JLabel();
        labelHomeAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLapanganTersedia = new javax.swing.JTable();
        buttonLogOut = new javax.swing.JButton();
        labelUsername1 = new javax.swing.JLabel();
        comboxTanggal = new javax.swing.JComboBox<>();
        labelLapanganTersedia = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        comboxBulan = new javax.swing.JComboBox<>();
        labelTahun = new javax.swing.JLabel();
        comboxTahun = new javax.swing.JComboBox<>();
        labelJenis = new javax.swing.JLabel();
        comboxJenis = new javax.swing.JComboBox<>();
        buttonBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCek.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonCek.setText("Cek");
        buttonCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 130, 40));

        buttonDataPelanggan.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPelanggan.setText("Data Pelanggan");
        buttonDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 40));

        buttonDataLapangan.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataLapangan.setText("Data Lapangan");
        buttonDataLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataLapanganActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 40));

        buttonDataBooking.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataBooking.setText("Data Booking");
        buttonDataBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataBookingActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 40));

        buttonDataPembayaran.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        buttonDataPembayaran.setText(" Data Pembayaran");
        buttonDataPembayaran.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDataPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDataPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 40));

        labelTanggal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTanggal.setText("Tanggal*");
        getContentPane().add(labelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 130, 30));

        labelHomeAdmin.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labelHomeAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHomeAdmin.setText("HOME");
        getContentPane().add(labelHomeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        tableLapanganTersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Lapangan", "Alamat", "Jenis", "Status"
            }
        ));
        tableLapanganTersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLapanganTersediaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLapanganTersedia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 570, 420));

        buttonLogOut.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 40));

        labelUsername1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        labelUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsername1.setText("username");
        getContentPane().add(labelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 150, 30));

        comboxTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(comboxTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 130, 30));

        labelLapanganTersedia.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        labelLapanganTersedia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLapanganTersedia.setText("Lapangan Tersedia");
        getContentPane().add(labelLapanganTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 30));

        labelBulan.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelBulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelBulan.setText("Bulan*");
        getContentPane().add(labelBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 130, 30));

        comboxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxBulanActionPerformed(evt);
            }
        });
        getContentPane().add(comboxBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 130, 30));

        labelTahun.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelTahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTahun.setText("Tahun*");
        getContentPane().add(labelTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 130, 30));

        comboxTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTahunActionPerformed(evt);
            }
        });
        getContentPane().add(comboxTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 130, 30));

        labelJenis.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        labelJenis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJenis.setText("Jenis");
        getContentPane().add(labelJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 130, 30));

        comboxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxJenisActionPerformed(evt);
            }
        });
        getContentPane().add(comboxJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 130, 30));

        buttonBooking.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        buttonBooking.setText("Booking");
        buttonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBookingActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 130, 40));

        pack();
    }// </editor-fold>                        

    private void buttonDataBookingActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void buttonDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        this.dispose();
        new PelangganFrame().setVisible(true);
    }                                                   

    private void buttonDataLapanganActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        this.dispose();
        new LapanganFrame().setVisible(true);
    }                                                  

    private void buttonDataPembayaranActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Model.UserSession.clearSession();
        this.dispose();
        new ViewLogin().setVisible(true);
    }                                            

    private void comboxTanggalActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void comboxBulanActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void comboxTahunActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void comboxJenisActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void buttonCekActionPerformed(java.awt.event.ActionEvent evt) {                                          
        loadLapanganTersedia();
    }                                         

    private void buttonBookingActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void tableLapanganTersediaMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  


    private void setupHomeLapangan() {
        isiComboTanggal();
        isiComboBulan();
        isiComboTahun();
        comboxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Semua", "Badminton", "Futsal", "Basket", "Voli"
        }));
        tableLapanganTersedia.setRowHeight(24);
        loadLapanganTersedia();
    }

    private void isiComboTanggal() {
        String[] tanggal = new String[31];
        for (int i = 0; i < 31; i++) {
            tanggal[i] = String.valueOf(i + 1);
        }
        comboxTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(tanggal));
        comboxTanggal.setSelectedItem(String.valueOf(java.time.LocalDate.now().getDayOfMonth()));
    }

    private void isiComboBulan() {
        String[] bulan = new String[] {
            "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"
        };
        comboxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(bulan));
        comboxBulan.setSelectedItem(String.valueOf(java.time.LocalDate.now().getMonthValue()));
    }

    private void isiComboTahun() {
        int tahunSekarang = java.time.LocalDate.now().getYear();
        String[] tahun = new String[] {
            String.valueOf(tahunSekarang),
            String.valueOf(tahunSekarang + 1),
            String.valueOf(tahunSekarang + 2)
        };
        comboxTahun.setModel(new javax.swing.DefaultComboBoxModel<>(tahun));
    }

    private void loadLapanganTersedia() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[] {"ID", "Nama Lapangan", "Alamat", "Jenis", "Status", "Harga/Jam"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String jenisDipilih = comboxJenis.getSelectedItem() == null
                ? "Semua"
                : comboxJenis.getSelectedItem().toString();

        try {
            for (Model.Lapangan lapangan : lapanganController.getLapanganTersedia()) {
                if (!"Semua".equals(jenisDipilih)
                        && !jenisDipilih.equals(lapangan.getJenisLapangan())) {
                    continue;
                }

                model.addRow(new Object[] {
                    lapangan.getIdLapangan(),
                    lapangan.getNamaLapangan(),
                    lapangan.getAlamatLapangan(),
                    lapangan.getJenisLapangan(),
                    lapangan.getStatusLapangan(),
                    lapangan.getHargaPerJam()
                });
            }
            tableLapanganTersedia.setModel(model);
        } catch (RuntimeException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Gagal memuat lapangan",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewHomeAdmin().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonBooking;
    private javax.swing.JButton buttonCek;
    private javax.swing.JButton buttonDataBooking;
    private javax.swing.JButton buttonDataLapangan;
    private javax.swing.JButton buttonDataPelanggan;
    private javax.swing.JButton buttonDataPembayaran;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JComboBox<String> comboxBulan;
    private javax.swing.JComboBox<String> comboxJenis;
    private javax.swing.JComboBox<String> comboxTahun;
    private javax.swing.JComboBox<String> comboxTanggal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelHomeAdmin;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JLabel labelLapanganTersedia;
    private javax.swing.JLabel labelTahun;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JTable tableLapanganTersedia;
    // End of variables declaration                   
}
